export interface MXGridColumn {
    field: string;
    name?: string;
    resizable?: boolean;
    width?: number;
    filterable?: boolean;
    // sortable?: boolean;
    // subName?: string;
    // isPinned?: boolean;
    // dataType?: MX_ADMIN_TABLE_DATA_TYPES;
    // coloring?: boolean;
    // editable?: boolean;
    // hasAction?: boolean;
    // actionNames?: string[];
    // icon?: string;
    // removable?: boolean;
    // copyable?: boolean;
    // showInfoIcon?: boolean;
    // isHidden?: boolean;
    // isDisabled?: boolean;
    // isView?: boolean;
    // fontWeight?: number;
    // pattern?: string;
    // maxLength?: number;
    // port?: boolean;
    // mask?: any;
    // min?: number;
    // max?: number;
    // required?: boolean;
    // tooltipPosition?: { x?: 'left' | 'right', y?: 'top' | 'bottom' };
    // showEditBtn?: boolean;
    // autocomplete?: boolean;
    // states?: { trueState: string; falseState: string; };
  }